THEME = {
    "bg": "#f4efe6",
    "bg_alt": "#f7f2ea",
    "card": "#ffffff",
    "panel": "#fff8ed",
    "text": "#1f2937",
    "muted": "#6b7280",
    "accent": "#0f766e",
    "accent_soft": "#eaf4ee",
    "border": "#e7e1d7",
    "shadow": "0 18px 50px rgba(15, 23, 42, 0.08)",
}

SKILL_KEYWORD_MAP = {
    "python": "Python",
    "sql": "SQL",
    "excel": "Excel",
    "data visualization": "Data Visualization",
    "visualization": "Data Visualization",
    "figma": "Figma",
    "user research": "User Research",
    "wireframing": "Wireframing",
    "javascript": "JavaScript",
    "html": "HTML",
    "css": "CSS",
    "react": "React",
    "node": "NodeJS",
    "node.js": "NodeJS",
    "communication": "Communication",
    "teamwork": "Teamwork",
    "problem solving": "Problem Solving",
    "project management": "Project Management",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "machine learning": "Machine Learning",
    "product design": "Product Design",
    "customer support": "Customer Support",
    "design thinking": "Design Thinking",
    "stakeholder management": "Stakeholder Management",
    "digital marketing": "Digital Marketing",
    "human resources": "Human Resources",
    "customer success": "Customer Success",
    "devops": "DevOps",
    "testing": "Testing",
    "cloud architecture": "Cloud Architecture",
    "data engineering": "Data Engineering",
    "legal compliance": "Legal Compliance",
    "sales": "Sales",
    "training": "Training",
    "leadership": "Leadership",
    "user experience": "User Experience",
    "business analysis": "Business Analysis",
    "recruiting": "Recruiting",
    "accessibility": "Accessibility",
    "performance management": "Performance Management",
    "data operations": "Data Operations",
    "security": "Security",
}

SKILL_OPTIONS = sorted(set(SKILL_KEYWORD_MAP.values()))
